package pairmatching.model;

public enum ProgramStatus {
	SHOW_FUNCTIONS,
	SELECT_FUNCTION,
	SHOW_PAIR_MATCHING_BOARD_FOR_MATCHING,
	INPUT_COURSE_LEVEL_MISSION,
	SHOW_PAIRS_RESULT,
	ASKING_REMATCHING,
	SHOW_PAIR_MATCHING_BOARD_FOR_SEARCHING,
	SHOW_PAIR_CLEAN
}
